# Generated by Django 5.1.2 on 2024-11-02 05:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('isbn', models.CharField(help_text='Enter a valid 10 or 13 digit ISBN', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be either 10 or 13 digits', regex='^\\d{10}(\\d{3})?$')])),
                ('published_at', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='catalog.author')),
                ('genre', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='catalog.genre')),
                ('publisher', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='catalog.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
