# Generated by Django 5.1.2 on 2024-11-03 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/drbktnxop/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1730624632/Missing-book-cover_ixkada.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/drbktnxop/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1730624632/Missing-book-cover_ixkada.jpg', max_length=255, null=True),
        ),
    ]
