# Generated by Django 5.1.2 on 2024-11-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_favorite_books'),
        ('catalog', '0002_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='catalog.book'),
        ),
    ]
